name: Deploy to AWS Lambda
on: workflow_dispatch

env:
  AWS_REGION: eu-north-1
  FUNCTION_NAME: shortener

jobs:
  deploy:
    name: Deploy
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and zip
        run: |
          GOOS=linux GOARCH=arm64 go build -tags lambda.norpc -o bootstrap ./cmd/link-shortener
          zip deploy.zip bootstrap .env

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy zip file to AWS Lambda
        run: |
          aws lambda update-function-code --function-name ${{ env.FUNCTION_NAME }} --zip-file fileb://deploy.zip
